### ISSUE TITLE
Getting a 404 Error

### ISSUE THREAD

**Issue by sirshr00my** [mohankumarpaluru/oracle-freetier-instance-creation#16]
List of instances is pulled and I see log entries in the api log on the oracle portal, but getting the following error in UNHANDLED_ERROR.log:

> status: 404
> code: NotAuthorizedOrNotFound
> message: Authorization failed or requested resource not found.

I have already deleted the whole folder and recreated the steps needed.

**Comment by mohankumarpaluru** [comment]
@sirshr00my  if its listing instances as you said then the issue is not related to API key but something related to the launch_instance part of the script. Can you please let me know whether you are trying to acquire a ARM or Micro instance and provide the error from below  

add the below line after [line 428  in `main.py`](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/blob/facf66ecc36bc21bacfa8b2a5540e898835b459f/main.py#L428) 
```python
print(srv_err)
```
and execute the script with below command 
```bash
source .venv/bin/activate
python3 main.py
```

this should print more detailed message and what resource is not entered properly.

**Comment by sirshr00my** [comment]
@mohankumarpaluru thanks for the quick reply.

Here is the output:

> {'target_service': 'compute', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'D1B60A11CCA44E51BE22C706147EBB16/36CF4E529EC4B65A1B9CC3B5AC218583/A8B5BCE9668DD2AC761DFD5BB379690E', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'launch_instance', 'timestamp': '2024-05-24T07:31:51.772849+00:00', 'client_version': 'Oracle-PythonSDK/2.126.4', 'request_endpoint': 'POST https://iaas.eu-zurich-1.oraclecloud.com/20160918/instances', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance for details on this operation's requirements. If you are unable to resolve this compute issue, please contact Oracle support and provide them this full error message."}
> Traceback (most recent call last):
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 398, in launch_instance
>     launch_instance_response = compute_client.launch_instance(
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/core/compute_client.py", line 6236, in launch_instance
>     return self.base_client.call_api(
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 535, in call_api
>     response = self.request(request, allow_control_chars, operation_name, api_reference_link)
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 726, in request
>     self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 891, in raise_service_error
>     raise exceptions.ServiceError(
> oci.exceptions.ServiceError: {'target_service': 'compute', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'D1B60A11CCA44E51BE22C706147EBB16/36CF4E529EC4B65A1B9CC3B5AC218583/A8B5BCE9668DD2AC761DFD5BB379690E', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'launch_instance', 'timestamp': '2024-05-24T07:31:51.772849+00:00', 'client_version': 'Oracle-PythonSDK/2.126.4', 'request_endpoint': 'POST https://iaas.eu-zurich-1.oraclecloud.com/20160918/instances', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance for details on this operation's requirements. If you are unable to resolve this compute issue, please contact Oracle support and provide them this full error message."}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 443, in <module>
>     launch_instance()
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 439, in launch_instance
>     handle_errors("launch_instance", data, logging_step5)
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 272, in handle_errors
>     raise Exception("Error: %s" % data)
> Exception: Error: {'status': 404, 'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.'}

**Comment by mohankumarpaluru** [comment]
I tried to reproduce this using ARM without success. The logs do not offer helpful insights either, thanks to Oracle linking Resource Not Found and Authentication errors. This complicates pinpointing the root issue. 

Could you verify the availability of Ubuntu 22.0 for ARM in your region? Additionally, please share your oci.env configuration here.

**Comment by sirshr00my** [comment]
These are the region/AD for Zurich and the desired image/shape:

![image](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/37252029/f7262278-5083-4044-908d-e24a6600b737)
![image](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/37252029/27467e2e-ca0b-49c9-af40-990406c3b55a)

oci.env:

`# OCI Configuration
OCI_CONFIG=/home/ubuntu/oracle-freetier-instance-creation/oci_config
OCT_FREE_AD=AD-1
DISPLAY_NAME=displayname (redacted)
# The other free shape is AMD: VM.Standard.E2.1.Micro
OCI_COMPUTE_SHAPE=VM.Standard.A1.Flex
REQUEST_WAIT_TIME_SECS=60
SSH_AUTHORIZED_KEYS_FILE=/home/ubuntu/oracle-freetier-instance-creation/id_rsa.pub
# SUBNET_ID to use in case running in local or a non E2.1.Micro instance
OCI_SUBNET_ID=ocid1.vcn.oc1.eu-zurich-1.(...) (redacted)
OCI_IMAGE_ID=
# The following will be ignored if OCI_IMAGE_ID is specified
OPERATING_SYSTEM=Canonical Ubuntu
OS_VERSION=22.04

# Gmail Notification
NOTIFY_EMAIL=False
EMAIL=abc@gmail
EMAIL_PASSWORD=16characterswithoutspaces
`

**Comment by mohankumarpaluru** [comment]
@sirshr00my can you please pull the latest code and try once more ?

**Comment by sirshr00my** [comment]
unfortunately still the same...

> status: 404
> code: NotAuthorizedOrNotFound
> message: Authorization failed or requested resource not found.

> {'target_service': 'compute', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'E68A7E34FDBE44EE91DB384927164BD3/E393523F49BF2BF23A9230DA66587CA9/411BB893CD0FBDD5D9239F776C14510A', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'launch_instance', 'timestamp': '2024-06-05T14:53:45.746036+00:00', 'client_version': 'Oracle-PythonSDK/2.128.0', 'request_endpoint': 'POST https://iaas.eu-zurich-1.oraclecloud.com/20160918/instances', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance for details on this operation's requirements. If you are unable to resolve this compute issue, please contact Oracle support and provide them this full error message."}
> Traceback (most recent call last):
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 402, in launch_instance
>     launch_instance_response = compute_client.launch_instance(
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/core/compute_client.py", line 6236, in launch_instance
>     return self.base_client.call_api(
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 535, in call_api
>     response = self.request(request, allow_control_chars, operation_name, api_reference_link)
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 726, in request
>     self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
>   File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 891, in raise_service_error
>     raise exceptions.ServiceError(
> oci.exceptions.ServiceError: {'target_service': 'compute', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'E68A7E34FDBE44EE91DB384927164BD3/E393523F49BF2BF23A9230DA66587CA9/411BB893CD0FBDD5D9239F776C14510A', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'launch_instance', 'timestamp': '2024-06-05T14:53:45.746036+00:00', 'client_version': 'Oracle-PythonSDK/2.128.0', 'request_endpoint': 'POST https://iaas.eu-zurich-1.oraclecloud.com/20160918/instances', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance for details on this operation's requirements. If you are unable to resolve this compute issue, please contact Oracle support and provide them this full error message."}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 451, in <module>
>     launch_instance()
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 447, in launch_instance
>     handle_errors("launch_instance", data, logging_step5)
>   File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 276, in handle_errors
>     raise Exception("Error: %s" % data)
> Exception: Error: {'status': 404, 'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.'}

**Comment by mohankumarpaluru** [comment]
if you are already running it from a ARM instance , you dont need to add the subnet details ,remove it from oci.env and try again.

Also can you go to your VPC and check the number of subnets avaialble there ?

**Comment by sirshr00my** [comment]
Wow, just removing the subnet ID did the trick... Sorry for the work I generated and thanks a lot for your support!

**Comment by mohankumarpaluru** [comment]
No problem, glad it finally worked, I'll add it to readme to don't add subnet explicitly if it's in Micro.
