### ISSUE TITLE
After the sript runs for a few hours I get a INFO - LimitExceeded , exiting the program

### ISSUE THREAD

**Issue by Mrsalai** [mohankumarpaluru/oracle-freetier-instance-creation#17]
After the sript runs for a few hours I get a INFO - LimitExceeded , exiting the program in the launch instance.log.

**Comment by mohankumarpaluru** [comment]
@Mrsalai LimitExceeded supposed to be occur when we already reached our free tier limit. Incase you didnt get the instance but still its quitting with this error then Oracle probably did some changes to the API response.

can you please add the below statements after [line 430 in Main file](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/blob/facf66ecc36bc21bacfa8b2a5540e898835b459f/main.py#L430C17-L430C77) and re-run the setup ?

```python
                logging_step5.info("Message: %s ", srv_err.message,)
                logging_step5.info("status: %s ", srv_err.status)
```


When the script stops again , please provide the new logs here

**Comment by Mrsalai** [comment]
Its:       400 code: LimitExceeded message: The following service limits were exceeded: standard-a1-memory-count, standard-a1-memory-regional-count, standard-a1-core-count, standard-a1-core-regional-count. Request a service limit increase from the service limits page in the console.

**Comment by mohankumarpaluru** [comment]
Check your console if you have an ARM instance and also check if there is a `INSTANCE _CREATED` file in your project directory

**Comment by Mrsalai** [comment]
It did not create an instance

**Comment by mohankumarpaluru** [comment]
then it's probably issue with Oracle ,  Nothing we can do with the script

**Comment by TheFlash787** [comment]
@Mrsalai Do you already have _any_ instance in your Oracle? I wanted to make another instance, but hit this error. The script hard-codes 4cores and 24gb, so if you have a small instance already, it won't fit -- the script can be edited though.

**Comment by Mrsalai** [comment]
Nope, I have 0 instances, But I did google it and found this stackoverflow post: https://stackoverflow.com/questions/72439600/oci-a1-flex-free-tier-limit-exceeded/72439791#72439791

**Comment by mohankumarpaluru** [comment]
> Nope, I have 0 instances, But I did google it and found this stackoverflow post: https://stackoverflow.com/questions/72439600/oci-a1-flex-free-tier-limit-exceeded/72439791#72439791

okay I'm hoping that checking the list of instances when we get limit exceeded error and only exiting if there is an instance would solve this issue but if there is some error at listing instances as well , then there is nothing we could do

**Comment by Mrsalai** [comment]
Sounds good, please update us with your progress :)

**Comment by mohankumarpaluru** [comment]
@Mrsalai try the code from `LimitExceeded-false-positive-fix` branch , it should fix the issue but I haven't tested it yet.

**Comment by Mrsalai** [comment]
Hey, sorry for the late reply, I just wanted to make sure it is working.
No issues so far.
Thanks
