### ISSUE TITLE
ERROR, script not working

### ISSUE THREAD

**Issue by Sermatty** [mohankumarpaluru/oracle-freetier-instance-creation#26]
**Describe the bug**

Hello,

I wanted to check if the script was working, but I noticed that the logs were completely empty. Therefore, I executed the following commands:

source .venv/bin/activate
python3 main.py
However, I encountered the following error:

Traceback (most recent call last):
  File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 67, in <module>
    config = oci.config.from_file(oci_config_path)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/config.py", line 120, in from_file
    invalid_key_file_path_checker(config, expanded_file_location, profile_name)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/config.py", line 224, in invalid_key_file_path_checker
    raise InvalidKeyFilePath(message)
oci.exceptions.InvalidKeyFilePath: Config file /home/ubuntu/oracle-freetier-instance-creation/oci_config is invalid: the key_file's value '</home/ubuntu/oracle-freetier-instance-creation/oci_api_private_key.pem> # TODO' at line 6 must be a valid file path. For more info about config file and how to get required information, see https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm

**Instance Type (please complete the following information):**
 - ARM 4 core and 24 of ram
 - Micro Second Instance: yes
 - Custom Image or default: ubuntu 22

**Environment (please complete the following information):**
 - Micro Instance or Local: VM.Standard.E2.1.Micro
 - OS: ubuntu
 - Version: 22

**Additional context**
here's my oci.env config:

# OCI Configuration
OCI_CONFIG=/home/ubuntu/oracle-freetier-instance-creation/oci_config
OCT_FREE_AD=AD-1,AD-2,AD-3
DISPLAY_NAME=main
# The other free shape is AMD: VM.Standard.E2.1.Micro
OCI_COMPUTE_SHAPE=VM.Standard.A1.Flex
SECOND_MICRO_INSTANCE=True
REQUEST_WAIT_TIME_SECS=600
SSH_AUTHORIZED_KEYS_FILE=/home/ubuntu/oracle-freetier-instance-creation/id_rsa.pub
# SUBNET_ID to use ONLY in case running in local or a non E2.1.Micro instance 
OCI_SUBNET_ID=
OCI_IMAGE_ID=
# The following will be ignored if OCI_IMAGE_ID is specified
OPERATING_SYSTEM=Canonical Ubuntu
OS_VERSION=22.0

**Comment by mohankumarpaluru** [comment]
it clear says that the oci API private key is not present. double check if it's placed in the correct location

**Comment by Sermatty** [comment]
![image](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/95446647/5aeb7395-6bf9-4123-8bec-553c0a6ff17a)

**Comment by Sermatty** [comment]
i followed the tutorial, and it should be present

**Comment by Sermatty** [comment]
this is the what the ls command shows

LICENSE             launch_instance.log  oci_api_private_key.pem  sample_oci_config
README.md           main.py              oci_config               setup_and_info.log
email_content.html  oci.env              requirements.txt         setup_init.sh

**Comment by mohankumarpaluru** [comment]
is your direcor

> ![image](https://private-user-images.githubusercontent.com/95446647/342792103-5aeb7395-6bf9-4123-8bec-553c0a6ff17a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzA5NzgsIm5iZiI6MTcxOTMzMDY3OCwicGF0aCI6Ii85NTQ0NjY0Ny8zNDI3OTIxMDMtNWFlYjczOTUtNmJmOS00MTIzLThiZWMtNTUzYzBhNmZmMTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE1NTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YjkzMmM0MGVjZjIwOWQ5NTQ0MzAyMWFlMDEwMGRkYjM5YWViZjQzNDk3NzQ1OWI2MTM5ZDNiMTdkOGU4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AsKwOP9HpTZHt-RWcreeEGI3sIUQXpXOKUtijocfWrk)

whats the project location?
is it `/home/ubuntu/oracle-freetier-instance-creation/` or something different?

**Comment by Sermatty** [comment]
yes it is, can you check if the permission for the key and config are right?
![image](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/95446647/f4442f9c-d1ca-4eb9-9de7-79b689116f6f)

**Comment by Sermatty** [comment]
ok, I think i found the error; I removed the comment .TODO in the oci_config file, now it's popolating the log with the message:

2024-06-26 08:52:36,212 - INFO - Command: launch_instance--
Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'}

is it correct?
