### ISSUE TITLE
Couldn't find any logs waiting 60 secs before checking again

### ISSUE THREAD

**Issue by a-w-1806** [mohankumarpaluru/oracle-freetier-instance-creation#27]
**Describe the bug**
When running `./setup_init.sh rerun` I immediately get `Couldn't find any logs waiting 60 secs before checking again` and after like a minute I get `Unhandled Exception Occurred.`. I don't get any local log file either.

**Expected behavior**
It should either successfully run, or leave some error log.

**Instance Type (please complete the following information):**
 - ARM or Micro: ARM
 - Micro Second Instance: yes
 - Custom Image or default: default

**Environment (please complete the following information):**
 - Micro Instance or Local: Micro Instance
 - OS: Ubuntu
 - Version: [optional]

**Screenshots**

**Additional context**
And sending email does not work either.

**Comment by mohankumarpaluru** [comment]
Damn you are right, thanks for catching it. Did you test it ?

**Comment by mohankumarpaluru** [comment]
Thanks again.Since I have already obtained the instance, testing the script has become challenging, I should plan to write some unit test cases for script's functionality soon.
