### ISSUE TITLE
New instance ad-1 22.04 ubuntu amd with newest download 

### ISSUE THREAD

**Issue by duduws** [mohankumarpaluru/oracle-freetier-instance-creation#28]
The script encountered an unhandled error and exited unexpectedly.

Please re-run the script by executing './setup_init.sh rerun'.

And raise a issue on GitHub if its not already existing:
https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/issues

 And include the following error message to help us investigate and resolve the problem:

status: 401
code: NotAuthenticated
message: Failed to verify the HTTP(S) Signature

**Comment by mohankumarpaluru** [comment]
please recreate the API key and try

**Comment by duduws** [comment]
> please recreate the API key and try

                                                                                                                                                              ./setup_init.sh rerun
Previous Log files deleted.
Couldn't find any logs waiting 60 secs before checking again
Unhandled Exception Occurred.
root@instance-20240630-1123:/home/ubuntu/oracle-freetier-instance-creation-main#                                                                                                                                                              nano UNHANDLED_ERROR.log
  GNU nano 6.2                                                                                                 UNHANDLED_ERROR.log
The script encountered an unhandled error and exited unexpectedly.

Please re-run the script by executing './setup_init.sh rerun'.

And raise a issue on GitHub if its not already existing:
https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/issues

 And include the following error message to help us investigate and resolve the problem:

status: 401
code: NotAuthenticated
message: The required information to complete authentication was not provided or was incorrect.

**Comment by duduws** [comment]
> please recreate the API key and try

Thank you, did it and worked. craeted the instance but where can i find the ppk key to connect in my arm instance?

**Comment by duduws** [comment]
Thank you.
