### ISSUE TITLE
Run this on a local machine?

### ISSUE THREAD

**Issue by kaiser62** [mohankumarpaluru/oracle-freetier-instance-creation#3]
`you need an existing subnet ID for ARM instance creation. `

Problem is in my region, it says, `Out of capacity for shape VM.Standard.E2.1.Micro`

Is there way to run this script on my local ubuntu machine and configure the subnet id in environment?

**Comment by mohankumarpaluru** [comment]
yes that's very simple to do , you should comment out lines 299 to 301 and configure your subnet in oci_subnet_id. Here is the link to the specific section of the script: [GitHub - main.py](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/blob/85b3ec065a91bb66206933a12a6bd58941446118/main.py#L299C1-L303C53).

let me know if you encounter any issues. I also should make a to-do list soon with list of features.
