### ISSUE TITLE
"Cant find logs"

### ISSUE THREAD

**Issue by F-alling** [mohankumarpaluru/oracle-freetier-instance-creation#30]
**Describe the bug**
A clear and concise description of what the bug is. Paste the unhandled_exception.log content if there is any that's generated.

I start the script with ./setup_init.sh script, it then run apt update.
It then Gets requirements, and after downloading them errors out.

```
Couldn't find any logs waiting 60 secs before checking again
Unhandled Exception Occurred.

```

**Expected behavior**
No Error

**Instance Type (please complete the following information):**
 - ARM
 - Micro Second Instance: No
 - Custom Image or default: Custom (Canonical-Ubuntu-22.04-aarch64-2024.04.17-0)

**Environment (please complete the following information):**
 - Micro Instance or Local: Local
 - OS: [e.g. Ubuntu , Oracle Linux] Ubuntu
 - Version: [optional] 22.04

**Screenshots**

**Additional context**

**Comment by mohankumarpaluru** [comment]
Do you see any Unhandled Exception log file ?

**Comment by F-alling** [comment]
No

**Comment by mohankumarpaluru** [comment]
did you add the subnet ?

**Comment by F-alling** [comment]
yes

**Comment by mohankumarpaluru** [comment]
can you run it manually? 

Activate env and run the python file

**Comment by F-alling** [comment]
I ran `main.py` and it then was missing modules.

**Comment by mohankumarpaluru** [comment]
what do you mean you ran and it was missing modules ?


do this 
```
source .venv/bin/activate
python3 main.py
```

**Comment by F-alling** [comment]
```
Traceback (most recent call last):
  File "/home/falling/ociarm/oracle-freetier-instance-creation/main.py", line 57, in <module>
    raise ValueError("oci.env has spaces in values which is not acceptable")
ValueError: oci.env has spaces in values which is not acceptable

```

**Comment by mohankumarpaluru** [comment]
hope thats clear enough for you resolve your issue , if not please go through the readme again
