### ISSUE TITLE
don't know if it's working

### ISSUE THREAD

**Issue by Sermatty** [mohankumarpaluru/oracle-freetier-instance-creation#33]
hi, i have been running the script since 26 of june. but I got nothing, is this normal?
btw i'm trying to get a vps in italy, milan

**Comment by lftzab** [comment]
Demand for Freetier Arm instances is very high, a lot of people use scripts like this to get an instance simultaneously, and patience is the key.
Check if the script generates logs to ensure it's working, good luck.

**Comment by Sermatty** [comment]
got this in the log, i'm trying to get an instance every 10 m, what should I do?
`2024-08-13 15:06:07,541 - INFO - Command: launch_instance--
Output: {'status': 429, 'code': 'TooManyRequests', 'message': 'Too many requests for the user'}
2024-08-13 15:16:08,575 - INFO - Command: launch_instance--
Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'}
2024-08-13 15:26:09,583 - INFO - Command: launch_instance--
Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'}
`

**Comment by naus3a** [comment]
> got this in the log, i'm trying to get an instance every 10 m, what should I do? `2024-08-13 15:06:07,541 - INFO - Command: launch_instance-- Output: {'status': 429, 'code': 'TooManyRequests', 'message': 'Too many requests for the user'} 2024-08-13 15:16:08,575 - INFO - Command: launch_instance-- Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'} 2024-08-13 15:26:09,583 - INFO - Command: launch_instance-- Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'} `

that log entry means the script is doing its job, but there is simply no available resources. I guess the options are:

1. waiting
2. upgrading to *pay as you go* and see if you get more resources in there. (don't have direct experience, but considering doing it myself)
