### ISSUE TITLE
The use of SECOND_MICRO_INSTANCE

### ISSUE THREAD

**Issue by dsakura** [mohankumarpaluru/oracle-freetier-instance-creation#38]
**Describe the bug**
This isnt a bug, but a doubt. The "SECOND_MICRO_INSTANCE=False" have to be True just if I already have one ampere machine right? And have some limitation from storage? The istance running the script is using 100gb.

Many thanks

**Comment by mohankumarpaluru** [comment]
SECOND_MICRO_INSTANCE is meant for usage when you are running the script to get your second Micro Instance , when you already have a running Micro Instance.

So the script won't say the instance already exists and continues trying to create a second instance. 

The boot volume size is not configurable via the script yet, it assigns a default 50 GB storage.

**Comment by dsakura** [comment]
micro instance you mean the ampere micro instance right? since I necessarily need an instance to run the script. And good to know about the 50gb default. Many thanks again
