### ISSUE TITLE
Script not running ? Logs remain empty.

### ISSUE THREAD

**Issue by FLOKHOME** [mohankumarpaluru/oracle-freetier-instance-creation#4]
Hello and thank you for the project.
Unfortunately I can't get it to work. I have created the configuration, executed the script - no errors.
But the log files (launch_instance.log and setup_and_info.log) remain empty.

**oci.env:**
![oci env](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/c01aec76-4753-4ab2-9e3f-482f5b4abe05)

**Folder:**
![structure](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/87884b19-28c7-4483-b00c-0a19377e9381)

**Script-Output**
![Script-output](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/3794390e-15f7-4ca4-b8ad-598fb1af54e7)

Have I overlooked something or done something wrong?

**Comment by mohankumarpaluru** [comment]
this is probably due to improper `oci_config` file 

check if your file is having 6 lines and you mentioned the key file path properly, here is a [sample_oci_config](https://raw.githubusercontent.com/mohankumarpaluru/oracle-freetier-instance-creation/main/sample_oci_config)

**Comment by FLOKHOME** [comment]
**Here is the content (censored):**
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaasu........
fingerprint=89:8c:48:18:c6:XXXXXXXX
tenancy=ocid1.tenancy.oc1..aaaaaaaa.......
region=eu-frankfurt-1
key_file=/home/ubuntu/oracle-freetier-instance-creation/oci_api_private_key.pem

**Comment by mohankumarpaluru** [comment]
try running the main.py file, if you encounter any errors, share the error msg here 


To activate the environment and execute the Python file, you can use the following commands once you are in project root directory:
```bash
source .venv/bin/activate
python3 main.py
```

**Comment by FLOKHOME** [comment]
**Seems to be a problem with the key ?!**

Traceback (most recent call last):
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/signer.py", line 53, in load_private_key
    return serialization.load_pem_private_key(secret, pass_phrase, backend=backend)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 494, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/oracle-freetier-instance-creation/main.py", line 52, in <module>
    iam_client = oci.identity.IdentityClient(config)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/identity/identity_client.py", line 90, in __init__
    signer = Signer(
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/signer.py", line 255, in __init__
    self.private_key = load_private_key_from_file(private_key_file_location, pass_phrase)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/signer.py", line 33, in load_private_key_from_file
    return load_private_key(private_key_data, pass_phrase)
  File "/home/ubuntu/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/signer.py", line 86, in load_private_key
    raise InvalidPrivateKey("The provided key is not a private key, or the provided passphrase is incorrect.")
oci.exceptions.InvalidPrivateKey: The provided key is not a private key, or the provided passphrase is incorrect.
(.venv) ubuntu@ubuntu-micro:~/oracle-freetier-instance-creation$

**Comment by FLOKHOME** [comment]
Found !
Error 40....40 cm in front of the screen...
I downloaded the API private key, but did not enter the content 1:1 in the "oci_api_private_key.pem"...

**Comment by FLOKHOME** [comment]
tail -f launch_instance.log

2024-03-11 10:02:22,144 - INFO - Command: launch_instance
Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.'}
2024-03-11 10:04:23,133 - INFO - Command: launch_instance
Output: {'status': 500, 'code': 'InternalError', 'message': 'Out of host capacity.

**Comment by mohankumarpaluru** [comment]
great. I'll update the bash script to handle OCI_CONFIG errors and provide informative feedback to users

**Comment by FLOKHOME** [comment]
I have one more question:
The AD is always AD-1, AD-2 etc, not AD1, AD2 ?
Is the "-" relevant?

**Comment by FLOKHOME** [comment]
![AD-Domains](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/3b377443-3b14-4fba-af6a-f60797e61fc2)

**Comment by mohankumarpaluru** [comment]
> ![AD-Domains](https://private-user-images.githubusercontent.com/115228322/311664983-3b377443-3b14-4fba-af6a-f60797e61fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTMyMTIsIm5iZiI6MTcxMDE1MjkxMiwicGF0aCI6Ii8xMTUyMjgzMjIvMzExNjY0OTgzLTNiMzc3NDQzLTNiMTQtNGZiYS1hZjZhLWY2MDc5N2U2MWZjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMDI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTMxOTdhYjkwMjk0ZTUzMmU1YWNlMGZkMzY1ODk4MmFkMzIxNTgzMGM1MTMyZGZiOTFkMDFjN2VjNjE3OTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.URPNO90vAnI6YhBF7_2cZEHr3B3PXY0OKoeRD01hCFY)

yes, `-` is essential. if you see the full availability domain names in the screenshot, you see they are actually ending with AD-1 , AD-2 , we are filtering these based on how they end

**Comment by FLOKHOME** [comment]
Also interesting:

![Error](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/5cb9a49c-6e74-431e-b397-6ec131f52db2)

**Comment by mohankumarpaluru** [comment]
> Also interesting:
> 
> ![Error](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/assets/115228322/5cb9a49c-6e74-431e-b397-6ec131f52db2)
> 

that's Oracle's measures for spam prevention. We wait for a brief period when encountering such occurrences before attempting a retry

**Comment by mohankumarpaluru** [comment]
Release v1.1 is handling these improper config file errors. Hence closing the issue
