### ISSUE TITLE
No option 'user' in section: 'DEFAULT'

### ISSUE THREAD

**Issue by Caduzin2005** [mohankumarpaluru/oracle-freetier-instance-creation#47]
**Describe the bug**
I know there are other 2 reports about this but both are closed with little to no information on how to solve, the script just stops and says the config file has no user, however i already remade the file 3 times and made sure the user was right
**Expected behavior**
Run script as normal
**Instance Type (please complete the following information):**
 - ARM or Micro:  ARM
 - Micro Second Instance: Yes
 - Custom Image or default: Custom, Oracle Linux 7.9

**Environment (please complete the following information):**
 - Micro Instance or Local:  Micro
 - OS: Ubuntu
 - Version:

**Screenshots**

**Additional context**
Tried the solution of removing /home/ , did not work

**Comment by mohankumarpaluru** [comment]
Hi @Caduzin2005,

This is defiently an issue with the setup, could you please verify the `oci_config` and `oci_env` files? They should resemble the following format, with only the values changed:

**oci_config:**
```
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaa
fingerprint=2e:c0:...
tenancy=ocid1.tenancy.oc1..aaaaaaaapoaaa
region=ap-hyderabad-1
key_file=/home/ubuntu/oracle-freetier-instance-creation/oci_api_private_key.pem
```

**oci.env:**
Ensure the path to `OCI_CONFIG` is correct:
```
# OCI Configuration
OCI_CONFIG=/home/ubuntu/oracle-freetier-instance-creation/oci_config
```

Also, please check that there are no spaces in any of your paths.

Thanks!

**Comment by Caduzin2005** [comment]
> Hi @Caduzin2005,
> 
> This is defiently an issue with the setup, could you please verify the `oci_config` and `oci_env` files? They should resemble the following format, with only the values changed:
> 
> **oci_config:**
> 
> ```
> [DEFAULT]
> user=ocid1.user.oc1..aaaaaaaa
> fingerprint=2e:c0:...
> tenancy=ocid1.tenancy.oc1..aaaaaaaapoaaa
> region=ap-hyderabad-1
> key_file=/home/ubuntu/oracle-freetier-instance-creation/oci_api_private_key.pem
> ```
> 
> **oci.env:** Ensure the path to `OCI_CONFIG` is correct:
> 
> ```
> # OCI Configuration
> OCI_CONFIG=/home/ubuntu/oracle-freetier-instance-creation/oci_config
> ```
> 
> Also, please check that there are no spaces in any of your paths.
> 
> Thanks!

Thank you very much, there was a typo on the oci config path, just noticied now, thanks
