### ISSUE TITLE
404 NotAuthorizedOrNotFound Error.

### ISSUE THREAD

**Issue by Muramono** [mohankumarpaluru/oracle-freetier-instance-creation#5]
Hello, I've tried following all the README instructions, but I am getting the follow error after running the script. Also for context I cannot currently get a oracle micro instance so I am running the script locally and modified the subnet with my own subnet and commented out line 299-301 as you suggested per another issue. I've tried to include all the possibly helpful info below, but let me know if you need anything else.

Launch_instance.log error
 - 2024-03-14 16:31:34,104 - INFO - Command: launch_instance
   Output: {'status': 404, 'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.'}

Things I've tried so far
- Checked that the API Key is correct.
- Checked that the filepath for the OCI_Config is correct in the oci.env
- checked that the filepath in the key_file filepath is correct in oci_config

oci.env for Reference 
      # OCI Configuration
      OCI_CONFIG=/home/mura/oracle-freetier-instance-creation/oci_config
      OCT_FREE_AD=AD-1,AD-2,AD-3
      DISPLAY_NAME=Server-Hoster
      REQUEST_WAIT_TIME_SECS=60
      SSH_AUTHORIZED_KEYS_FILE=/home/mura/oracle-freetier-instance-creation/id_rsa.pub
      OCI_IMAGE_ID=
      # The following will be ignored if OCI_IMAGE_ID is specified
      OPERATING_SYSTEM=Canonical Ubuntu
      OS_VERSION=22.04
      
      # Gmail Notification
      NOTIFY_EMAIL=True
      EMAIL=<censored>
      EMAIL_PASSWORD=<censored>

OCI_Config for reference
    [DEFAULT]
    user=ocid1.user.oc1..aaaaaaaay.........
    fingerprint=51:eb:.......
    tenancy=ocid1.tenancy.oc1..aaaaaaaab.......
    region=us-chicago-1
    key_file=/home/mura/oracle-freetier-instance-creation/oci_api_private_key.pem

Error Trace I get from running the main.py
- python3 main.py
Traceback (most recent call last):
  File "/home/mura/oracle-freetier-instance-creation/main.py", line 327, in launch_instance
    launch_instance_response = compute_client.launch_instance(
  File "/home/mura/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/core/compute_client.py", line 6238, in launch_instance
    return self.base_client.call_api(
  File "/home/mura/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/home/mura/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 726, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/home/mura/oracle-freetier-instance-creation/.venv/lib/python3.10/site-packages/oci/base_client.py", line 891, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'target_service': 'compute', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': '9DE8F85708534A04B4FE475491BB2AB2/87FFFB24B03C6218740AB77B1C59545A/967C940559C1AC9399787FC163002E11', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'launch_instance', 'timestamp': '2024-03-14T21:31:34.104507+00:00', 'client_version': 'Oracle-PythonSDK/2.124.1', 'request_endpoint': 'POST https://iaas.us-chicago-1.oraclecloud.com/20160918/instances', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Instance/LaunchInstance for details on this operation's requirements. If you are unable to resolve this compute issue, please contact Oracle support and provide them this full error message."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mura/oracle-freetier-instance-creation/main.py", line 373, in <module>
    launch_instance()
  File "/home/mura/oracle-freetier-instance-creation/main.py", line 369, in launch_instance
    handle_errors("launch_instance", data, logging_step5)
  File "/home/mura/oracle-freetier-instance-creation/main.py", line 216, in handle_errors
    raise Exception("Error: %s" % data)
Exception: Error: {'status': 404, 'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.'}

**Comment by mohankumarpaluru** [comment]
The issue might be an incorrect subnet ID. Please confirm that the oci_subnet_id variable on [line 302](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/blob/85b3ec065a91bb66206933a12a6bd58941446118/main.py#L302) matches the following pattern:
- `ocid1.subnet.oc1.<region>.<unique_ID>`

Double-check that there are no typos or extra characters in the subnet ID provided.

**Comment by Muramono** [comment]
Sorry I'm not super familiar with network stuff, but since I am using my local machine instead of a oracle mini VM I used ifconfig to find my netmask and set that as the subnet ID. My subnet that I get from that is formatted xxx.xxx.xxx.x . I'm also not sure if this would cause any issues, but I am trying to run this on a WSL ubuntu instance. Any other ideas?

**Comment by mohankumarpaluru** [comment]
@maciekniewielki 

okay that's your local subnet but we can't create the Instance in that subnet so you got to create a VPC in the Oracle Cloud Console, establish a subnet within it, and utilize the specific subnet's OCI ID in line 302 for seamless integration.


it's fairly simple process, try searching on how to create VPC/Subnet in Oracle cloud you should see some examples. let me know if you face any issues

**Comment by Muramono** [comment]
@mohankumarpaluru Thank you I got it working now with this. I actually already had a subnet setup, but I didn't fully understand which subnet was required for that step. Thank you for a very well documented and helpful github.
