### ISSUE TITLE
An exception occurred while running the script NoOptionError

### ISSUE THREAD

**Issue by gregvp00** [mohankumarpaluru/oracle-freetier-instance-creation#7]
_**Hello, I've attempted to execute the script after manually installing the requirements (as they weren't installed automatically with setup_init.sh), and now I'm encountering this error:**_

ubuntu@instance-20240329-1316:~/script/oracle-freetier-instance-creation$ python3 ./main.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 35, in <module>
    OCI_USER_ID = config.get('DEFAULT', 'user')
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'user' in section: 'DEFAULT'

### **Do you have any idea how to solve it? Thanks in advance :)**

**Comment by mohankumarpaluru** [comment]
@gregvp00 

This happens when the expected configuration option is missing from the configuration file.

check your oci_config file and see if it matches the [sample_oci_config](https://github.com/mohankumarpaluru/oracle-freetier-instance-creation/blob/85b3ec065a91bb66206933a12a6bd58941446118/sample_oci_config#L1C1-L6C80)

**Comment by mohankumarpaluru** [comment]
Improved the handling of CONFIG errors in script,

Please try the latest code and reopen it if its still unclear or a different issue.
