### ISSUE TITLE
About the DISPLAY_NAME

### ISSUE THREAD

**Issue by dsakura** [mohankumarpaluru/oracle-freetier-instance-creation#9]
Do I need to add the name of the current machine or the amp I want to create?

Thanks

**Comment by mohankumarpaluru** [comment]
it should the Arm instance name that you are going to create

**Comment by mohankumarpaluru** [comment]
> Okay, so I added it wrong, I put the same name. 

You can rename it later in the console, or you can reference it by instance type.

>  I was also unsure whether I need to fill in the OCI_IMAGE_ID, and if yes, what is the value to be ubuntu and ampere free tier.

The OCI_IMAGE_ID field is for those who require a specific OS and version other than the ones in the config. If you don't need a different one, you can leave it blank and it will still work.

**Comment by dsakura** [comment]
Perfect! If I need to restart the server, I need to restart the script right? Last one, sorry. And thanks again

**Comment by mohankumarpaluru** [comment]
> Perfect! If I need to restart the server, I need to restart the script right? Last one, sorry. And thanks again

what do you mean restart the server, kill the python program and re-run the bash script

**Comment by dsakura** [comment]
Sorry, error when typing, it was supposed to be "if I restart the server", do I need to run the script again or is it already configured to start with the system?
Thanks!

**Comment by mohankumarpaluru** [comment]
gotcha, you need to re-run it after you start the system.
